# A conda environment with all useful package for ctapipe developers
name: magic-lst1
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - astropy
  - black
  - bokeh
  - nbsphinx
  - ctapipe=0.12
  - gammapy=0.19.0
  - cython
  - graphviz
  - h5py
  - iminuit>=2
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib
  - numba
  - numpy>=1.17
  - numpydoc
  - pandas
  - pre-commit
  - protozfits=2.0
  - psutil
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scikit-learn
  - scipy
  - setuptools
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - tqdm
  - traitlets
  - uproot~=4.1
  - vitables
  - wheel
  - xz
  - zlib
  - zstandard
  - eventio>=1.5.0
  - corsikaio
  - pip:
      - lstchain~=0.9.6
      - ctapipe_io_magic~=0.4.7
      - ctaplot~=0.5.5
      - pyirf~=0.6.0
