# A conda environment with all useful package for ctapipe developers
name: magic-lst1
channels:
  - default
  - cta-observatory
dependencies:
  - python=3.7
  - pip
  - astropy
  - black
  - bokeh=1.0
  - conda-forge::nbsphinx
  - conda-forge::ctapipe=0.12
  - conda-forge::gammapy=0.19.0
  - cython
  - graphviz
  - h5py
  - iminuit>=2
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib
  - numba
  - numpy>=1.17
  - numpydoc
  - pandas
  - pre-commit
  - psutil
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scikit-learn
  - scipy
  - setuptools
  - sphinx=4.2
  - sphinx-automodapi
  - sphinx_rtd_theme
  - tqdm
  - traitlets
  - vitables
  - wheel
  - xz
  - zlib
  - zstandard
  - conda-forge::eventio>=1.5.0
  - conda-forge::corsikaio
  - pip:
      - lstchain~=0.9.6
      - ctapipe_io_magic~=0.4.4
      - uproot~=4.1
      - ctaplot~=0.5.5
      - pyirf~=0.6.0
