# A conda environment with all useful package for ctapipe developers
name: magic-lst
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - astropy=5
  - black
  - nbsphinx
  - ctapipe=0.19.2
  - gammapy=1.1
  - ctaplot~=0.6.4
  - h5py
  - ipython
  - jupyter
  - matplotlib=3.7
  - notebook
  - graphviz
  - iminuit>=2
  - joblib~=1.2.0
  - numpydoc
  - jinja2~=3.0.2
  - jupyterlab=3.5.0
  - pandas>=2
  - pre-commit
  - toml
  - tomli
  - protobuf=3.20
  - pydata-sphinx-theme
  - pyparsing
  - psutil
  - pytest
  - pytest-cov
  - pytest-dependency
  - pytest-runner
  - pyyaml
  - scipy~=1.11.4
  - scikit-learn=1.2
  - setuptools
  - sphinx
  - sphinx-automodapi
  - sphinx-design
  - sphinx_rtd_theme
  - numba>=0.56
  - uproot~=5.0
  - pymongo
  - pyirf~=0.10.0
  - ctapipe-io-magic~=0.5.4
  - lstchain~=0.10.5
