# A conda environment with all useful package for ctapipe developers
name: magic-lst
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - astropy-base
  - black
  - nbsphinx
  - ctapipe>=0.25.0
  - gammapy=1.1
  - ctaplot
  - h5py
  - ipython
  - jupyter
  - matplotlib
  - notebook
  - graphviz
  - iminuit>=2
  - joblib
  - numpydoc
  - jinja2~=3.0.2
  - jupyterlab=3.5.0
  - pandas
  - pre-commit
  - toml
  - tomli
  - protozfits
  - pydata-sphinx-theme
  - pyparsing
  - psutil
  - pytest
  - pytest-cov
  - pytest-dependency
  - pytest-runner
  - pyyaml
  - scipy
  - scikit-learn
  - setuptools<=71
  - sphinx
  - sphinx-automodapi
  - sphinx-design
  - sphinx_rtd_theme
  - numba>=0.56
  - uproot
  - pymongo
  - pyirf
