# A conda environment with all useful package for ctapipe developers
name: magic-lst
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - black
  - nbsphinx
  - numpy=1.21
  - ctapipe=0.12
  - gammapy=0.19.0
  - cython
  - graphviz
  - iminuit>=2
  - joblib
  - numpydoc
  - jupyterlab=3.5.0
  - pandas
  - pre-commit
  - protozfits=2.0
  - psutil
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scikit-learn
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - uproot~=4.1
  - corsikaio
  - pip:
      - lstchain~=0.9.6
      - ctapipe_io_magic~=0.4.7
      - ctaplot~=0.5.5
      - pyirf~=0.6.0
