# --- DATA FILES ---------------------------------------------------------------
# NOTE:
# - stereo_reco will store files in "DL1" folder ("_Link" is removed from hillas_h5)
# - train_rfs and train_rfs will look in "DL1_Link" folder instead
# - train_rfs is run on all files, so so "_run${run}_" is removed from hillas_h5
data_files:
  mc:
    train_sample:
      mask_sim: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/DL0_Link/gamma_diffuse/*_run${run}_*.simtel.gz'
      hillas_h5: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL1_Link/gamma_diffuse_train/*_run${run}_*.h5'
    test_sample:
      mask_sim: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/DL0_Link/gamma_00deg/*_run${run}_*.simtel.gz'
      hillas_h5: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL1_Link/gamma_00deg_test/*_run${run}_*.h5'
      reco_h5: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL2/gamma_00deg_test_reco/*_reco.h5'
  data:
    train_sample:
      mask_sim: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/DL0_Link/proton/*_run${run}_*.simtel.gz'
      hillas_h5: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL1_Link/proton_train/*_run${run}_*.h5'
    test_sample:
      mask_sim: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/DL0_Link/proton/*_run${run}_*.simtel.gz'
      hillas_h5: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL1_Link/proton_test/*_run${run}_*.h5'
      reco_h5: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL2/proton_test_reco/*_reco.h5'

# --- TELESCOPES ---------------------------------------------------------------
all_tels:
  tel_ids: [1, 2, 3, 4]
  tel_n: ['LST', 'MAGIC']
  tel_n_short: ['LST', 'M']
  stereo_id: -1

LST:
  tel_ids: [1, 2, 3, 4]
  cleaning_config:
    picture_thresh: 8
    boundary_thresh: 4
    keep_isolated_pixels: false
    min_number_picture_neighbors: 1
  camera_name: 'LSTCam'
  min_pixel: 5

MAGIC:
  tel_ids: [5, 6]
  use_MARS_cleaning: true
  cleaning_config:
    picture_thresh: 6
    boundary_thresh: 3.5
    find_hotpixels: false
    max_time_diff: 2.46
    max_time_off: 7.38
    use_sum: true
    use_time: true
  bad_pixel_config:
    pedestalLevel: 400
    destalLevelVariance: 4.5
    pedestalType: 'FromExtractorRndm'
  camera_name: 'MAGICCam'
  min_pixel: 5
  position: # MAGIC telescope positions in m wrt. to the center of CTA simulations
    5: [-27.24, -146.66, 50.0]
    6: [-96.44, -96.77, 51.0]

# --- GLOBAL -------------------------------------------------------------------
global:
  wrong_alt: 'tel_alt < 1.5707963267948966'

# --- TRAIN CLASSIFIER RF ------------------------------------------------------
classifier_rf:
  check_train_test: False
  save_dir: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/RFs/'
  joblib_name: 'classifier_rf.joblib'
  cuts: "(event_id > 0)"
  settings:
    n_estimators: 100
    min_samples_leaf: 10
    n_jobs: 3
  features: ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'r', 'psi', 'num_islands', 'h_max',
             'core_x', 'core_y', 'impact']
  fig_name: 'classifier_rf_gammaness'
  fig_size: [20, 10]
  test_file_n: 0

# --- TRAIN DIRECTION RF -------------------------------------------------------
direction_rf:
  check_train_test: False
  save_dir: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/RFs/'
  joblib_name: 'direction_rf.joblib'
  cuts: "(event_id > 0)"
  settings:
    n_estimators: 100
    min_samples_leaf: 10
    n_jobs: 3
  features:
    'disp': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'r', 'psi', 'h_max', 'core_x',
             'core_y', 'impact']
    'pos_angle_shift': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'r', 'psi', 'h_max',
                        'core_x', 'core_y', 'impact']
  fig_name_theta2: 'Direction_RF_theta2'
  fig_name_PSF_energy: 'Direction_RF_PSF_energy'
  fig_name_PSF_offset: 'Direction_RF_PSF_offset'
  fig_size: [12, 12]
  test_file_n: 20

# --- TRAIN ENERGY RF ----------------------------------------------------------
energy_rf:
  check_train_test: False
  save_dir: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/RFs/'
  joblib_name: 'energy_rf.joblib'
  cuts: "(event_id > 0)"
  settings:
    n_estimators: 100
    min_samples_leaf: 10
    n_jobs: 3
  features: ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'r', 'psi', 'intensity_width_1',
             'intensity_width_2', 'h_max', 'core_x', 'core_y', 'impact']
  fig_name: 'Energy_RF_migmatrix'
  fig_size: [30, 10]
  test_file_n: 0

# --- IRFs ---------------------------------------------------------------------
irfs:
  T_OBS: 50 # u.hour
  ALPHA: 0.2 # scaling between on and off region
  MAX_BG_RADIUS: 1.0 # u.deg
  cut_on_multiplicity: 2
  INITIAL_GH_CUT_EFFICENCY: 0.4
  MAX_GH_CUT_EFFICIENCY: 0.99
  GH_CUT_EFFICIENCY_STEP: 0.01
  MIN_GH_CUT_EFFICIENCY: 0.01
  theta_bins_exp_low: -1.9
  theta_bins_exp_high: 2.3005
  theta_bins_num: 50
  sensitivity_bins_exp_low: -1.9
  sensitivity_bins_exp_high: 2.31
  sensitivity_bins_num: 5
  max_files_gamma: 0
  max_files_proton: 0
  verbose: False
  INTENSITY_CUT: 50
  LEAKAGE1_CUT: 0.15
  gamma_dl2: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL2/gamma_00deg_test_reco_merged.h5'
  proton_dl2: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL2/proton_test_reco_merged.h5'
  consider_electron: True
  electron_dl2: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/DL2/electron_test_reco_merged.h5'
  save_dir: '/fefs/aswg/workspace/davide.depaoli/CTA-MC/Prod5/Analysis/4LST/8-4_nocuts/IRFs/'
  useless_cols: ['pixels_width_1', 'pixels_width_2', 'alt', 'alt_uncert', 'az', 'az_uncert', 'core_x', 'core_y', 'impact',
                 'core_uncert', 'h_max', 'h_max_uncert', 'is_valid', 'tel_ids', 'average_intensity', 'goodness_of_fit',
                 'disp_reco', 'disp_reco_err', 'az_reco_mean', 'alt_reco_mean', 'energy_reco_err',
                 'energy_reco_mean', 'event_class_1', 'event_class_0_mean', 'event_class_1_mean', 'r', 'r', 'phi',
                 'length', 'width', 'psi', 'skewness', 'kurtosis', 'slope', 'slope_err', 'intercept', 'intercept_err',
                 'deviation', 'num_islands']