# Configuration file to be used for stereo analysis of MAGIC data.
# In the several input_mask keys, one has to include files from
# both M1 and M2, since the MAGICEventSource will match the events
# to get the stereo events.

data_files:
    mc:
      train_sample:
        magic:
          input_mask: "/path/to/MC_train_files/GA*_Y_*.root"
          hillas_output: "/path/to/MC_train_files/MC_train_hillas.h5"
      test_sample:
        magic:
          input_mask: "/path/to/MC_test_files/GA*_Y_*.root"
          hillas_output: "/path/to/MC_test_files/MC_test_hillas.h5"
          reco_output: "/path/to/MC_test_files/MC_test_reco.h5"
    data:
      train_sample:
        magic:
          input_mask: "/path/to/data_train_files/20*_Y_*.root"
          hillas_output: "/path/to/data_train_files/data_train_hillas.h5"
      test_sample:
        magic:
          input_mask: "/path/to/data_test_files/20*_Y_*.root"
          hillas_output: "/path/to/data_test_files/data_test_hillas.h5"
          reco_output: "/path/to/data_test_files/data_test_reco.h5"

image_cleaning:
    magic:
        charge_thresholds:
            picture_thresh: 6
            boundary_thresh: 3.5
            min_number_picture_neighbors: 1

        time_thresholds:
            # 1.5 slices x 1.64 GHz
            max_time_diff: 2.46
            # 4.5 slices x 1.64 GHz
            max_time_off: 7.38
            min_number_neighbors: 1

energy_rf:
    save_name: "RFs/energy_rf.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt', 'az']

direction_rf:
    save_name: "RFs/direction_rf.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        'disp': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'h_max', 'alt', 'az']
        'pos_angle_shift': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'h_max', 'alt', 'az']

classifier_rf:
    save_name: "RFs/classifier_rf.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'n_islands', 'h_max', 'alt', 'az']

irf:
    output_name: "/path/to/IRF_file/outfile.fits"

source:
    name: "Crab"
    coordinates:
        ra_dec: [83.633083, 22.0145]

event_list:
    output_directory: "/path/to/output/directory"
    max_time_diff: 6.9e-4
    cuts:
        quality:
            l3rate: "80 < value < 1000"
            dc: "0 < value < 7e3"
        selection:
            "(event_id > 0) & (multiplicity > 1) & (event_class_0 > 0.8)"

spectrum:
    input_files: "/path/to/input/events*.fits"
    #exclude_region: {0 : [183.604, -8.708, 0.5]}
    spectral_model:
        power_law: {'index' : 2, 'amplitude' : 2.0e-11, 'reference' : 0.3}
        #log_parabola: {'alpha' : 2, 'amplitude' : 2.0e-11, 'beta' : 0.2, 'reference' : 0.3}
